# Generated by Django 4.2.30 on 2026-05-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skills', models.TextField()),
                ('target_job', models.CharField(max_length=200)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3+ years)')], default='beginner', max_length=20)),
                ('duration', models.CharField(choices=[('3months', '3 Months'), ('6months', '6 Months'), ('1year', '1 Year'), ('2years', '2 Years')], default='6months', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('overview', models.TextField()),
                ('roadmap_data', models.TextField()),
                ('total_weeks', models.IntegerField(default=0)),
                ('difficulty_score', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='roadmap_generator.roadmaprequest')),
            ],
        ),
    ]
